version: '3.8'

services:
  redis-master:
    image: redis:7.0-alpine
    container_name: redis-master
    command: redis-server --appendonly yes --protected-mode no
    ports:
      - "6379:6379"
    networks:
      - redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-replica-1:
    image: redis:7.0-alpine
    container_name: redis-replica-1
    command: redis-server --appendonly yes --replicaof redis-master 6379 --protected-mode no
    ports:
      - "6380:6379"
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-net

  redis-replica-2:
    image: redis:7.0-alpine
    container_name: redis-replica-2
    command: redis-server --appendonly yes --replicaof redis-master 6379 --protected-mode no
    ports:
      - "6381:6379"
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-net

  # --- INFRASTRUKTUR MONITORING (Sentinel - 3 Nodes) ---
  
  sentinel-1:
    image: bitnami/redis-sentinel:latest
    container_name: sentinel-1
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
      # Tidak ada password
    depends_on:
      - redis-master
    ports:
      - "26379:26379"
    networks:
      - redis-net

  sentinel-2:
    image: bitnami/redis-sentinel:latest
    container_name: sentinel-2
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
    networks:
      - redis-net

  sentinel-3:
    image: bitnami/redis-sentinel:latest
    container_name: sentinel-3
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge