services:
  # --- Node Utama (Master) ---
  redis-master:
    image: redis:8-alpine
    container_name: redis-master
    command: redis-server --appendonly yes --protected-mode no
    ports:
      - "6379:6379"
    networks:
      - redis-net

  # --- Node Replica 1 ---
  redis-replica-1:
    image: redis:8-alpine
    container_name: redis-replica-1
    command: redis-server --appendonly yes --replicaof redis-master 6379 --protected-mode no
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      - redis-net

  # --- Node Replica 2 ---
  redis-replica-2:
    image: redis:8-alpine
    container_name: redis-replica-2
    command: redis-server --appendonly yes --replicaof redis-master 6379 --protected-mode no
    ports:
      - "6381:6379"
    depends_on:
      - redis-master
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge